services:
    _defaults:
        autowire: true
        autoconfigure: true

    KimaiPlugin\FortnoxBundle\FortnoxBundle:
        autowire: true
        autoconfigure: true

    KimaiPlugin\FortnoxBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Resources,Tests,tests}'
